name: test
on: push
jobs:
  test:
    name: Integrate Fortanix
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@main
     - name: 🚀 Deploy Application
       run: echo "Deploying the app"
     - name: 🔍 Authenticate to Fortanix
       env:
          API_KEY: ${{ secrets.FORTANIX_API_KEY_SDKMS_CLI }}
       run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url https://amer.smartkey.io/sys/v1/session/auth \
               --header "Authorization:Basic $API_KEY")
          if [ "$response" -eq 200 ]; then
            echo "✅ API is running!"
          else
            echo "❌ API test failed with HTTP status: $response"
            exit 1
          fi
     - name: 🔍 Generate a new key
       env:
          API_KEY: ${{ secrets.FORTANIX_API_KEY_SDKMS_CLI }}
       run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url https://amer.smartkey.io/crypto/v1/keys \
               --header "Authorization:Basic $API_KEY"  --data '{
                                        "name": "github_actions",
                                        "description": "github actions",
                                        "key_size": 1024,
                                        "obj_type": "RSA",
                                         "key_ops": ["ENCRYPT", "DECRYPT", "SIGN", "VERIFY"]
                                      }')
          if [ "$response" -eq 201 ]; then
            echo "✅ Created a key"
          else
            echo "❌ API test failed with HTTP status: $response"
            exit 1
          fi
